language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lazarkalajdzic/docker-react -f Dockerfile.dev .

script:
  - docker run lazarkalajdzic/docker-react npm run test -- --coverage
